<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_SALIR</name>
   <tag></tag>
   <elementGuidId>de70ad17-52d0-4093-a294-14cf27fb9404</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'SALIR')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btnLogout.btn-danger</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4e1480ce-ab55-495c-b13f-0c77b4e42f24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://buzon.talisis.com/admin/salir</value>
      <webElementGuid>0c37dc69-2c7a-47ab-aaf7-f8052ea9d50f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btnLogout btn-danger</value>
      <webElementGuid>b77dd7ae-c223-486b-895e-eb992098ef24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SALIR</value>
      <webElementGuid>0b6c28b7-f9b2-4d66-9a04-f0865371f244</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;js flexbox flexboxlegacy canvas canvastext webgl no-touch geolocation postmessage no-websqldatabase indexeddb hashchange history draganddrop websockets rgba hsla multiplebgs backgroundsize borderimage borderradius boxshadow textshadow opacity cssanimations csscolumns cssgradients cssreflections csstransforms csstransforms3d csstransitions fontface generatedcontent video audio localstorage sessionstorage webworkers no-applicationcache svg inlinesvg smil svgclippaths&quot;]/body[1]/section[@class=&quot;main-container&quot;]/a[@class=&quot;btn btnLogout btn-danger&quot;]</value>
      <webElementGuid>cf47574b-78e2-4b5e-b8aa-3e4670a8c45d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'SALIR')]</value>
      <webElementGuid>864f9d98-fc8b-4c49-9af6-70f6f0b6ab9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mensajes'])[1]/following::a[1]</value>
      <webElementGuid>a8fa4241-5515-4c4b-ae08-573472bd212f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Roberto Sanchez Molina'])[1]/preceding::a[1]</value>
      <webElementGuid>310c771a-0f69-4d74-b785-11d3013f9779</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Administrar mensajes'])[1]/preceding::a[1]</value>
      <webElementGuid>6c98acf4-f5b6-4ec0-83a5-ec28bdd581cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SALIR']/parent::*</value>
      <webElementGuid>4cd4949f-c8b0-4bbc-b9d2-2953c894bb85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://buzon.talisis.com/admin/salir')]</value>
      <webElementGuid>b6fa73ca-9336-4c31-94e2-a6f062c00c20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/a</value>
      <webElementGuid>6e706113-58d7-4e88-b1e3-cdbcadd41460</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://buzon.talisis.com/admin/salir' and (text() = 'SALIR' or . = 'SALIR')]</value>
      <webElementGuid>09cabe3b-ffe7-424d-b2a6-d948114d283d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
