<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_SALIR</name>
   <tag></tag>
   <elementGuidId>de70ad17-52d0-4093-a294-14cf27fb9404</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'SALIR')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btnLogout.btn-danger</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6978fb6c-b37b-4b66-93cd-b71b3f3e2fe9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://buzon.talisis.com/admin/salir</value>
      <webElementGuid>083367a6-8003-43ea-8718-0eeb66ea0028</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btnLogout btn-danger</value>
      <webElementGuid>9fb553cd-4531-4728-b73f-54e1e5862830</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SALIR</value>
      <webElementGuid>34f4b11b-a120-44c5-be34-73a9e0af1aae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;js flexbox flexboxlegacy canvas canvastext webgl no-touch geolocation postmessage no-websqldatabase indexeddb hashchange history draganddrop websockets rgba hsla multiplebgs backgroundsize borderimage borderradius boxshadow textshadow opacity cssanimations csscolumns cssgradients cssreflections csstransforms csstransforms3d csstransitions fontface generatedcontent video audio localstorage sessionstorage webworkers no-applicationcache svg inlinesvg smil svgclippaths&quot;]/body[1]/section[@class=&quot;main-container&quot;]/a[@class=&quot;btn btnLogout btn-danger&quot;]</value>
      <webElementGuid>72351664-d1cd-4c15-af58-d2fb216db114</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'SALIR')]</value>
      <webElementGuid>b83855f3-8357-4877-b387-6ec12cd32495</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mensajes'])[1]/following::a[1]</value>
      <webElementGuid>b48ba378-bfe8-4352-ad3c-7dce84970e21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Roberto Sanchez Molina'])[1]/preceding::a[1]</value>
      <webElementGuid>c3b1cb68-e8f8-4971-8001-2d99da9974a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Administrar mensajes'])[1]/preceding::a[1]</value>
      <webElementGuid>9168e6fd-21f1-4543-aa60-7c3c9af128b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SALIR']/parent::*</value>
      <webElementGuid>74035b44-17ba-4b49-a1d6-dccff63b3443</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://buzon.talisis.com/admin/salir')]</value>
      <webElementGuid>acc8320f-f013-46bc-b6fe-f03bf5b8a6c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/a</value>
      <webElementGuid>451e68c6-eab8-449b-a6f6-939c91f96398</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://buzon.talisis.com/admin/salir' and (text() = 'SALIR' or . = 'SALIR')]</value>
      <webElementGuid>f0cabc20-4ecd-4277-ac1f-5eb7ac916924</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
